# Generated by Django 2.1.2 on 2019-01-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardRackCache',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sourceHash', models.CharField(max_length=50)),
                ('jsonStr', models.CharField(max_length=65536)),
            ],
        ),
    ]
